services:
  app:
    build: .
    # image: ghcr.io/walterrosa2/elos_email_inteligente:latest
    container_name: elos_app
    ports:
      - "8000:8000"
    volumes:
      - ./dados:/app/dados
      - ./.env:/app/.env
    restart: unless-stopped
